/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetAclResponseItem struct {
	ResourceId string `json:"resourceId,omitempty"`
	ResourceName string `json:"resourceName,omitempty"`
	Description string `json:"description,omitempty"`
	Roles []RoleData `json:"roles,omitempty"`
	// The date created
	Created string `json:"created,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	// The date last updated
	Modified string `json:"modified,omitempty"`
	ModifiedBy string `json:"modifiedBy,omitempty"`
}
