/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SparseValues struct {
	// The unique ID of the characteristics
	ValueId string `json:"valueId,omitempty"`
	// Item action refer to action perform using sparse values
	ItemAction string `json:"itemAction,omitempty"`
}
