/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClaimItem struct {
	ClaimName string `json:"claimName,omitempty"`
	Description string `json:"description,omitempty"`
}
