/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Defines the filters to apply to the results, this is dynamic, so you can specify any names that match your data. You can specify multiple criteria for each filter
type OrderSummaryGridFilterOptions struct {
	DisplayID []string `json:"DisplayID,omitempty"`
}
