/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QuoteItem struct {
	Id   string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	// The date item was created
	Created string `json:"created,omitempty"`
	// The date item was created
	QuoteLastUpdated   string            `json:"quoteLastUpdated,omitempty"`
	ProductId          string            `json:"productId,omitempty"`
	Description        string            `json:"description,omitempty"`
	ProductCandidate   *ProductCandidate `json:"productCandidate,omitempty"`
	PrePricedCandidate *ProductCandidate `json:"prePricedCandidate,omitempty"`
	// The identifier of the portfolio item that this QuoteItem relates to.
	PortfolioItemId string `json:"portfolioItemId,omitempty"`
	// the product specification for this offer
	OfferSpecification *interface{}         `json:"offerSpecification,omitempty"`
	CurrentPricing     *ICpqPricingResponse `json:"currentPricing,omitempty"`
	CurrentValidation  *ValidationResponse  `json:"currentValidation,omitempty"`
	// The portfolio action which is to be applied to the Quote.If no value is specified then the CPQ API will treat it as an Add. The only values which are allowed are <Add | Update | Delete>
	ItemAction string `json:"itemAction,omitempty"`

	// MNK MADE THIS - should be spec'd!
	MetaTypeLookup map[string]interface{} `json:"metaTypeLookup,omitempty"`
}
