/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetClaimsResponseItem struct {
	ClaimId string `json:"claimId,omitempty"`
	ClaimName string `json:"claimName,omitempty"`
	Description string `json:"description,omitempty"`
	// The date created
	Created string `json:"created,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	// The date last updated
	Modified string `json:"modified,omitempty"`
	ModifiedBy string `json:"modifiedBy,omitempty"`
}
