/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ITotalProfitSummary struct {
	Recurring *IPeriodProfitSummary `json:"Recurring,omitempty"`
	NonRecurring *IProfitSummary `json:"NonRecurring,omitempty"`
}
