/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserCharacteristicSelectionRule struct {
	// Contains the default value (optional) which is to be specified on the negotiated user defined characteristic. If the original specification does not contain the correct CPQ Behaviour structure to house a default value, then Content validation of the Framework Contract will fail.
	DefaultValue string `json:"defaultValue,omitempty"`
	// Contains the identifiers from the specification root element to the user defined characteristic (external or internal)
	Path []string `json:"path,omitempty"`
}
