/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AfterLocationCopyRequest struct {
	ProductCandidate *ProductCandidate `json:"productCandidate,omitempty"`
	SourceValue *ICharacteristicUse `json:"sourceValue,omitempty"`
	// The details of the location values of the copied products
	CopiedValues []ProductLocationData `json:"copiedValues,omitempty"`
}
