/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IPeriodProfitSummary struct {
	Monthly []IProfitSummary `json:"Monthly,omitempty"`
	Annualy []IProfitSummary `json:"Annualy,omitempty"`
	Weekly []IProfitSummary `json:"Weekly,omitempty"`
}
