/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProductCandidateForPricing struct {
	// The unique ID of the product candidate. Will be set during the database write operation if not provided
	ID string `json:"ID,omitempty"`
	// ID of the entity according to its specification
	EntityID string `json:"EntityID,omitempty"`
	// An array of related entities
	ChildEntity []IEntity `json:"ChildEntity,omitempty"`
	// An array of characteristic uses. Can be configurable characteristic or fact instances
	CharacteristicUse []ErrorUnknown `json:"CharacteristicUse,omitempty"`
	// An array of rating attributes
	RateAttribute []ErrorUnknown `json:"RateAttribute,omitempty"`
	// An array of configured value uses. These are user defined characteristic instances
	ConfiguredValue []ErrorUnknown `json:"ConfiguredValue,omitempty"`
	// An optional array of strings that represent other entities that this product is linked to
	LinkedEntity []ErrorUnknown `json:"LinkedEntity,omitempty"`
}
