/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type OrderSubmissionResponse struct {
	QuoteId string `json:"quoteId,omitempty"`
	QuoteReference string `json:"quoteReference,omitempty"`
	// The id of the order that this quote was generated from (for quotes with quoteType of 'change')
	OrderId string `json:"orderId,omitempty"`
	OrderStatus string `json:"orderStatus,omitempty"`
	OrderSubmissionDate time.Time `json:"orderSubmissionDate,omitempty"`
	QuoteLastUpdated time.Time `json:"quoteLastUpdated,omitempty"`
}
