/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Summary information of the non-recurring charges for the candidate
type IStandaloneActionBasedChargeSummary struct {
	Charge *IActionBasedStandaloneChargeItem `json:"Charge,omitempty"`
	// The minimum possible total of non-recurring charges for the candidate
	MinimumTotal float32 `json:"MinimumTotal,omitempty"`
	// The final total of non-recurring charges for the candidate
	FinalTotal float32 `json:"FinalTotal,omitempty"`
}
