/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OrderSummary struct {
	OrderKey string `json:"OrderKey,omitempty"`
	OrderSpecKey string `json:"OrderSpecKey,omitempty"`
	DisplayID string `json:"DisplayID,omitempty"`
	SubmissionDate string `json:"SubmissionDate,omitempty"`
	ClientID string `json:"ClientID,omitempty"`
	Status string `json:"Status,omitempty"`
	PONR string `json:"PONR,omitempty"`
	OrderItems []OrderItem `json:"OrderItems,omitempty"`
}
