/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The summary for a recurring charges by period
type IRecurringChargeSummary struct {
	Period []IPeriodSummary `json:"Period,omitempty"`
}
