/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetOrderEnrichmentTask200EnrichmentTasks struct {
	Name string `json:"name,omitempty"`
	InstanceId string `json:"instanceId,omitempty"`
	PhaseId string `json:"phaseId,omitempty"`
	User string `json:"user,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
	IsValid bool `json:"isValid,omitempty"`
}
