/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WorkFlowRequestBody struct {
	// The unique identifier
	Id string `json:"id,omitempty"`
	// Generalize messages for workflow API transition. The message body can be array or array of objects and should contain atleast one element
	Messages []ErrorUnknown `json:"messages,omitempty"`
}
