/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RoleDataItem struct {
	RoleId string `json:"roleId,omitempty"`
	RoleName string `json:"roleName,omitempty"`
}
