/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QuoteItemCopy200 struct {
	// The quote version number represented as the last updated timestamp
	QuoteLastUpdated string `json:"quoteLastUpdated,omitempty"`
	// The new quote item that had been copied
	NewQuoteItemId string `json:"newQuoteItemId,omitempty"`
}
