/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreateQuoteResponse struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	QuoteNumber string `json:"quoteNumber,omitempty"`
	Created string `json:"created,omitempty"`
	ContextData *interface{} `json:"contextData,omitempty"`
	Update string `json:"update,omitempty"`
	CustomerRef string `json:"customerRef,omitempty"`
	Items []ErrorUnknown `json:"items,omitempty"`
	QuoteType string `json:"quoteType,omitempty"`
	SpecLookup []ErrorUnknown `json:"specLookup,omitempty"`
	OrderId string `json:"orderId,omitempty"`
	CpqOrderId string `json:"cpqOrderId,omitempty"`
	CpqSupplementalOrderId string `json:"cpqSupplementalOrderId,omitempty"`
	SubmissionDate string `json:"submissionDate,omitempty"`
	RootId string `json:"rootId,omitempty"`
	QuoteHistory []ErrorUnknown `json:"quoteHistory,omitempty"`
	PricingDate string `json:"pricingDate,omitempty"`
	LastUserName string `json:"lastUserName,omitempty"`
	Status string `json:"status,omitempty"`
}
