/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IConfiguredValue struct {
	// The name of the configured value
	Value string `json:"Value,omitempty"`
	// The entered detail for the configured value
	ValueDetail string `json:"ValueDetail,omitempty"`
}
