/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type StatusObjectDbStatusDataFileVersion struct {
	Major float32 `json:"major,omitempty"`
	Minor float32 `json:"minor,omitempty"`
}
