/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PortfolioByLocation struct {
	LocationId string `json:"locationId,omitempty"`
	LocationName string `json:"locationName,omitempty"`
	PortfolioItems []PortfolioItemByLocation `json:"portfolioItems,omitempty"`
	TotalRecurringCharge []SummarisedPeriodicities `json:"totalRecurringCharge,omitempty"`
	TotalNonRecurringCharge float32 `json:"totalNonRecurringCharge,omitempty"`
}
