/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OrderItemSummariesParameters struct {
	Filter *OrderSummaryGridFilterOptions `json:"filter,omitempty"`
	PaginationOptions *OrderSummaryGridPaginationOptions `json:"paginationOptions,omitempty"`
	// Defines the fields to return, this is dynamic, so you can specify any names that match your location data
	LocationFormat []string `json:"locationFormat,omitempty"`
}
