/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CustomerAccount struct {
	Id string `json:"id,omitempty"`
	AccountNumber string `json:"accountNumber,omitempty"`
	AccountName string `json:"accountName,omitempty"`
	BillingAddress *CustomerAddress `json:"billingAddress,omitempty"`
	Description string `json:"description,omitempty"`
	CustomerContact []CustomerContact `json:"customerContact,omitempty"`
}
