/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type StatusObjectDbStatus struct {
	Db string `json:"db,omitempty"`
	Collections float32 `json:"collections,omitempty"`
	Objects float32 `json:"objects,omitempty"`
	AvgObjectSize float32 `json:"avgObjectSize,omitempty"`
	DataSize float32 `json:"dataSize,omitempty"`
	StorageSize float32 `json:"storageSize,omitempty"`
	NumExtents float32 `json:"numExtents,omitempty"`
	Indexes float32 `json:"indexes,omitempty"`
	IndexSize float32 `json:"indexSize,omitempty"`
	FileSize float32 `json:"fileSize,omitempty"`
	NsSizeMB float32 `json:"nsSizeMB,omitempty"`
	DataFileVersion *StatusObjectDbStatusDataFileVersion `json:"dataFileVersion,omitempty"`
	ExtentFreeList *StatusObjectDbStatusExtentFreeList `json:"extentFreeList,omitempty"`
	Ok float32 `json:"ok,omitempty"`
}
