/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserDefinedCharacteristics struct {
	// Unique characteristic id of the Characteristics
	CharacteristicId string `json:"characteristicId,omitempty"`
	// User Area for the characteristics
	UseArea string `json:"useArea,omitempty"`
	// Item action refer to action perform using sparse characteristics
	ItemAction string `json:"itemAction,omitempty"`
	// An array of user defined characteristic values. Can be configurable characteristic  values or fact instances
	Values []UserDefinedValues `json:"values,omitempty"`
}
