/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GenericOrderItem struct {
	ID string `json:"ID,omitempty"`
	EntityID string `json:"EntityID,omitempty"`
	PortfolioItemID string `json:"PortfolioItemID,omitempty"`
	ItemAction string `json:"ItemAction,omitempty"`
	ItemSource string `json:"ItemSource,omitempty"`
	ChargeType string `json:"ChargeType,omitempty"`
	ExactType string `json:"ExactType,omitempty"`
	Periodicity string `json:"Periodicity,omitempty"`
	CharacteristicUse []interface{} `json:"CharacteristicUse,omitempty"`
	ConfiguredValue []interface{} `json:"ConfiguredValue,omitempty"`
	Rate *interface{} `json:"Rate,omitempty"`
	ChildOrderItem []interface{} `json:"ChildOrderItem,omitempty"`
}
