/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QuoteSummaryInnerQuoteItemSummaries struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	NonRecurringCharge float32 `json:"nonRecurringCharge,omitempty"`
	RecurringCharge float32 `json:"recurringCharge,omitempty"`
}
