/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Location struct {
	// The location ID
	LocationId string `json:"locationId,omitempty"`
	// The location name
	Name string `json:"name,omitempty"`
	// The Street number
	StreetNrFirst string `json:"streetNrFirst,omitempty"`
	// The Street name
	StreetName string `json:"streetName,omitempty"`
	// The state/province
	StateOrProvince string `json:"stateOrProvince,omitempty"`
	// The country
	Country string `json:"country,omitempty"`
	// The postal/zip code
	PostCode string `json:"postCode,omitempty"`
}
