/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The summary for a period
type IPeriodSummary struct {
	// Name of the period the summary relates to
	Name string `json:"Name,omitempty"`
	// Minimum total for the given period
	MinimumTotal string `json:"MinimumTotal,omitempty"`
	// Maximum total for the given period
	MaximumTotal string `json:"MaximumTotal,omitempty"`
}
