/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Response that groups the customer portfolio by location
type PortfolioByLocationResponse struct {
	// Portfolio items grouped by location, each item will contain all portfolio items for that particular location and the total price it costs in that location
	PortfoliosByLocation []PortfolioByLocation `json:"portfoliosByLocation,omitempty"`
}
