/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ICharacteristicUse struct {
	// The name of the characteristic
	UseArea string `json:"UseArea,omitempty"`
	// An array of characteristic values
	Value []ICharacteristicValue `json:"Value,omitempty"`
	// The characteristic id
	CharacteristicID string `json:"CharacteristicID,omitempty"`
}
