/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Summary information of the non-recurring charges for the candidate
type IActionBasedStandaloneChargeItem struct {
	Rate *IEntityRate `json:"Rate,omitempty"`
	// The type of charge for the action based standalone charge item
	ChargeType string `json:"ChargeType,omitempty"`
	// The exact type of the action based standalone charge item
	ExactType string `json:"ExactType,omitempty"`
	// The name of the action based standalone charge item
	ChargeName string `json:"ChargeName,omitempty"`
}
