/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RelatedOffersPackage struct {
	ID string `json:"ID,omitempty"`
	BusinessID string `json:"BusinessID,omitempty"`
	CrossSellPatternName *RelatedOffersPackageCrossSellPatternName `json:"CrossSellPatternName,omitempty"`
	UpSellPatternName *RelatedOffersPackageUpSellPatternName `json:"UpSellPatternName,omitempty"`
	EntitySummaryList *interface{} `json:"EntitySummaryList,omitempty"`
	MissingEntities *interface{} `json:"MissingEntities,omitempty"`
}
