/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FcValidationItem struct {
	// The path to the data element in framework contract
	ContextPath string `json:"contextPath,omitempty"`
	// For some scenarios it is possible to provide additional information that will prevent any future calls from failing. This property will contain that additional description which will be translated into the language of the calling client
	ResolutionText string `json:"resolutionText,omitempty"`
	// The unique code which describes the exception which occurred or is specified as SUCCESS for success responses
	ResponseCode string `json:"responseCode,omitempty"`
	// A fuller description of the exception which occurred that is translated to the requested language of the calling client. If the response is a success response this property will contain the word SUCCESS translated into the language of the calling client.
	ResponseText string `json:"responseText,omitempty"`
}
