/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreateContractModel struct {
	// The body of the Framework Contract which contains the selection rules for filtering down a product specification to a framework contract specification
	Document *interface{} `json:"document,omitempty"`
	// End date from when the Contract is no longer effect represented in ISO 8601 format
	EndDate string `json:"endDate,omitempty"`
	// digit identifier of the Framework Contract. It is possible for multiple documents to have the same identifier as there will be old versions of the contracts in the database
	FcId string `json:"fc_Id,omitempty"`
	// The (optional) name of the Framework Contract e.g. 'Bronze' or 'Silver' used to identify
	Name string `json:"name,omitempty"`
	// Start date from when the Contract is to take effect represented in ISO 8601 format
	StartDate string `json:"startDate,omitempty"`
}
