/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FcValidationResponse struct {
	// Indicates the given framework contract is valid or not. If true, the responseItems property will not exist, if false, the transformedSpecifications property will not exist
	IsValid bool `json:"isValid,omitempty"`
	// If an API call is to return a data response it will be found here
	TransformedSpecifications []interface{} `json:"transformedSpecifications,omitempty"`
	// If an API call is to return a data response it will be found here
	ValidationItems *interface{} `json:"validationItems,omitempty"`
}
