/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QuoteItemSummaryInner struct {
	Id string `json:"id,omitempty"`
	Created string `json:"created,omitempty"`
	Items *interface{} `json:"items,omitempty"`
}
