/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Details of the priced product candidate
type IPricingServiceResponseEntity struct {
	// Any child items the priced entity may contain
	ChildEntity []IPricingServiceResponseEntity `json:"ChildEntity,omitempty"`
	// The type of charge for the priced entity
	ChargeType string `json:"ChargeType,omitempty"`
	// The exact type of the priced entity
	ExactType string `json:"ExactType,omitempty"`
	Rate *IEntityRate `json:"Rate,omitempty"`
	// The periodicity applied to the priced entity
	Periodicity string `json:"Periodicity,omitempty"`
	// Flag to indicate whether or not the priced entity has been paid
	HasBeenPaid bool `json:"HasBeenPaid,omitempty"`
	// The type of the cost for the priced entity
	CostType string `json:"CostType,omitempty"`
}
