/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreteQuoteBody struct {
	CustomerRef string `json:"customerRef,omitempty"`
	Items []ErrorUnknown `json:"items,omitempty"`
	QuoteType string `json:"quoteType,omitempty"`
}
