/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OrderCandidate struct {
	OrderID string `json:"OrderID,omitempty"`
	Customer *interface{} `json:"Customer,omitempty"`
	OrderItem []OrderCandidate `json:"OrderItem,omitempty"`
	OrderContext []interface{} `json:"OrderContext,omitempty"`
	Limits []string `json:"limits,omitempty"`
}
