/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AttachmentLink struct {
	Id string `json:"id,omitempty"`
	// The title of the attachment
	Title string `json:"title,omitempty"`
	// The url link to the attachment
	Url string `json:"url,omitempty"`
	// An enum representing the source, CPQ=0, External=1
	Source string `json:"source,omitempty"`
	// The priority of the task
	QuoteId string `json:"quoteId,omitempty"`
}
