/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Defines the fields to return, this is dynamic, so you can specify any names that match your location data
type LocationFieldOptions struct {
	LocationId *interface{} `json:"locationId,omitempty"`
	Country *interface{} `json:"country,omitempty"`
}
