/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RestResponse struct {
	// The type of exception which occurred. For success responses this will not be present
	ExceptionType string `json:"exceptionType,omitempty"`
	// The http status code which describes the response
	HttpStatus float32 `json:"httpStatus,omitempty"`
	// For some scenarios it is possible to provide additional information that will prevent any future calls from failing. This property will contain that additional description which will be translated into the language of the calling client.
	ResolutionText string `json:"resolutionText,omitempty"`
	// If an API call is to return a data response it will be found here
	ResponseBody *interface{} `json:"responseBody,omitempty"`
	// The unique code which describes the exception which occurred or is specified as SUCCESS for success responses
	ResponseCode string `json:"responseCode,omitempty"`
	// A fuller description of the exception which occurred that is translated to the requested language of the calling client. If the response is a success response this property will contain the word SUCCESS translated into the language of the calling client.
	ResponseText string `json:"responseText,omitempty"`
}
