/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Assignee struct {
	Id string `json:"Id,omitempty"`
	// The assignee's first name
	FirstName string `json:"FirstName,omitempty"`
	// The assignee's last name
	LastName string `json:"LastName,omitempty"`
}
