/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type StandaloneDiscount struct {
	// The identifier of the standalone discount in UUID format
	DiscountGuid string `json:"discountGuid,omitempty"`
	// Contains the collection of discounts rates to include in the framework contract specification
	DiscountName string `json:"discountName,omitempty"`
	// The optional collection of standalone discounts which are to be retained on the negotiated specification. If none are specified then they will not be available.
	StandaloneDiscountSelectionRule []StandaloneDiscountSelectionRule `json:"standaloneDiscountSelectionRule,omitempty"`
}
