/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QuoteSummaryInnerQuoteHistory struct {
	Reference string `json:"reference,omitempty"`
	Type_ string `json:"type,omitempty"`
	Status string `json:"status,omitempty"`
	LastActivityDate string `json:"lastActivityDate,omitempty"`
}
