/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetOffersByClassificationResponseInner struct {
	Guid string `json:"guid,omitempty"`
	Name string `json:"name,omitempty"`
	Entities []interface{} `json:"entities,omitempty"`
}
