/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PortfolioItemSummary struct {
	Id string `json:"id,omitempty"`
	EntityId string `json:"entityId,omitempty"`
	EntityName string `json:"entityName,omitempty"`
	OrderedData string `json:"orderedData,omitempty"`
	ActivationDate string `json:"activationDate,omitempty"`
	Status string `json:"status,omitempty"`
	TotalRecurringCharge float32 `json:"totalRecurringCharge,omitempty"`
	TotalNonRecurringCharge float32 `json:"totalNonRecurringCharge,omitempty"`
}
