/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RateableItemSelectionRule struct {
	// Contains the identifiers starting from the specification root element to the Discount structure that is to be retained on the negotiated specification.
	Path []string `json:"path,omitempty"`
}
