/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Offering struct {
	// The collection of entities that are to be retained on the negotiated specification.
	CardinalityRules []CardinalityRule `json:"cardinalityRules,omitempty"`
	// The collection of TSpecCharUse structure that are to be retained on the negotiated specification
	CharacteristicSelectionRules []ConfigurableCharacteristicSelectionRule `json:"characteristicSelectionRules,omitempty"`
	// The collection of charges that are to be retained on the negotiated specification
	ChargeSelectionRules []RateableItemSelectionRule `json:"chargeSelectionRules,omitempty"`
	// The collection of discounts that are to be retained on the negotiated specification
	DiscountSelectionRules []RateableItemSelectionRule `json:"discountSelectionRules,omitempty"`
	// The collection of TConfigurableFact structures that are to be retained on the negotiated specification
	FactSelectionRules []FactSelectionRule `json:"factSelectionRules,omitempty"`
	// The identifier of the product specification which is in UUID format.
	OfferId string `json:"offerId,omitempty"`
	// The name of the offer which has been selected - this is purely a UI concern
	OfferName string `json:"offerName,omitempty"`
	// The collection of TUserDefinedCharacteristics that are to be retained on the negotiated specification. This structure can be used to specify both internal and externally defined user characteristics.
	UserDefinedCharacteristicSelectionRules []UserCharacteristicSelectionRule `json:"userDefinedCharacteristicSelectionRules,omitempty"`
}
