/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QuoteSummaryInner struct {
	Id string `json:"id,omitempty"`
	QuoteNumber string `json:"quoteNumber,omitempty"`
	QuoteType string `json:"quoteType,omitempty"`
	Status string `json:"status,omitempty"`
	NonRecurringCharge float32 `json:"nonRecurringCharge,omitempty"`
	RecurringCharge float32 `json:"recurringCharge,omitempty"`
	Created string `json:"created,omitempty"`
	QuoteItemSummaries []QuoteSummaryInnerQuoteItemSummaries `json:"quoteItemSummaries,omitempty"`
	QuoteHistory []QuoteSummaryInnerQuoteHistory `json:"quoteHistory,omitempty"`
}
