/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BulkAssignRolesToResourcesInvalidDataType struct {
	ResponseCode string `json:"responseCode,omitempty"`
	ResponseText string `json:"responseText,omitempty"`
	ExceptionType string `json:"exceptionType,omitempty"`
	ResolutionText string `json:"resolutionText,omitempty"`
}
