/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserDefinedValues struct {
	// The  value of the user defined value
	Value string `json:"value,omitempty"`
	// Item action refer to action perform using sparse values
	ItemAction string `json:"itemAction,omitempty"`
}
