/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QuoteCopyResponse struct {
	// The id of the new quote created
	NewQuoteId string `json:"newQuoteId,omitempty"`
	Mappings []QuoteCopyItemMapping `json:"mappings,omitempty"`
}
