/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SparseCreateQuoteItemValidationRestErrorResponse struct {
	// The type of exception which occurred. For success responses this will not be present
	ExceptionType string `json:"exceptionType,omitempty"`
	// The unique code which describes the exception which occurred or is specified as SUCCESS for success responses
	ResponseCode string `json:"responseCode,omitempty"`
	// A fuller description of the exception which occurred that is translated to the requested language of the calling client. If the response is a success response this property will contain the word SUCCESS translated into the language of the calling client.
	ResponseText string `json:"responseText,omitempty"`
	ResponseBody []string `json:"responseBody,omitempty"`
}
