/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Document struct {
	// Collection of offerings (product specifications such as Packages) which are to be a part of the negotiated specification. There must be at least one offering structure per Framework Contract
	Offerings []Offering `json:"offerings,omitempty"`
	// The optional collection of standalone discounts which are to be retained on the negotiated specification. If none are specified then they will not be available.
	StandaloneDiscounts []StandaloneDiscount `json:"standaloneDiscounts,omitempty"`
}
