/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PortfolioItem struct {
	ActivationDate string `json:"ActivationDate,omitempty"`
	OrderedDate string `json:"OrderedDate,omitempty"`
	Status string `json:"Status,omitempty"`
	EntityName string `json:"EntityName,omitempty"`
	ContextualParameter []string `json:"ContextualParameter,omitempty"`
	ID string `json:"ID,omitempty"`
	EntityID string `json:"EntityID,omitempty"`
	ChildEntity []PortfolioItem `json:"ChildEntity,omitempty"`
	CharacteristicUse []interface{} `json:"CharacteristicUse,omitempty"`
	RateAttribute []interface{} `json:"RateAttribute,omitempty"`
	ConfiguredValue []interface{} `json:"ConfiguredValue,omitempty"`
	Meta *interface{} `json:"meta,omitempty"`
}
