/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Task struct {
	Id string `json:"Id,omitempty"`
	// The id of the person assigned to the task
	AssigneeId string `json:"AssigneeId,omitempty"`
	// Last date of activity
	ActivityDate string `json:"ActivityDate,omitempty"`
	// Description of the task
	Description string `json:"Description,omitempty"`
	// The current status of the task
	Status string `json:"Status,omitempty"`
	// The subject of the task
	Subject string `json:"Subject,omitempty"`
}
