/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SparseRequest struct {
	Quantity float32 `json:"quantity,omitempty"`
	// An array products to be configured
	Products []Products `json:"products,omitempty"`
}
