/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IItemPriceSummary struct {
	// Summary information of ignored charges for the candidate
	IgnoredCharges []interface{} `json:"IgnoredCharges,omitempty"`
	// Summary information of the recurring charges for the candidate.This has to be any, as the pricing service could return an object or an array
	RecurringCharges []IRecurringChargeSummary `json:"RecurringCharges,omitempty"`
	NonRecurringCharges *INonRecurringChargeSummary `json:"NonRecurringCharges,omitempty"`
	ActionBasedCharges *INonRecurringActionBasedChargeSummary `json:"ActionBasedCharges,omitempty"`
	StandaloneCharges *IStandaloneActionBasedChargeSummary `json:"StandaloneCharges,omitempty"`
	// Summary information of ignored costs for the candidate
	IgnoredCosts []interface{} `json:"IgnoredCosts,omitempty"`
	// Summary information of the recurring costs for the candidate.This has to be any, as the pricing service could return an object or an array
	RecurringCosts []IRecurringCostSummary `json:"RecurringCosts,omitempty"`
	NonRecurringCosts *INonRecurringCostSummary `json:"NonRecurringCosts,omitempty"`
}
