/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QuoteCopyItemMapping struct {
	// The id of the original item
	OriginalId string `json:"originalId,omitempty"`
	// The id of the duplicated item
	NewId string `json:"newId,omitempty"`
}
