/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IEntityRate struct {
	// The unique identifier for the entity rate
	ID string `json:"ID,omitempty"`
	// The type for the entity rate
	Type_ string `json:"Type,omitempty"`
	// The start date applied to the entity rate
	StartDate string `json:"StartDate,omitempty"`
	// The end date applied to the entity rate
	EndDate string `json:"EndDate,omitempty"`
	// The charge value of the entity rate
	Value string `json:"Value,omitempty"`
	// The cost value of the entity rate
	CostValue string `json:"CostValue,omitempty"`
}
