/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GenericOrder struct {
	OrderID string `json:"OrderID,omitempty"`
	Customer *Customer `json:"Customer,omitempty"`
	OrderItem []GenericOrderItem `json:"OrderItem,omitempty"`
}
