/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FinancialSummaryResponse struct {
	Id string `json:"id,omitempty"`
	GroupBy *GroupBy `json:"groupBy,omitempty"`
	TotalSummary *TotalSummary `json:"totalSummary,omitempty"`
	Containers []Container `json:"containers,omitempty"`
	QuoteItems []QuoteItem `json:"quoteItems,omitempty"`
}
