/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QuoteType struct {
	// enum value, 0 = sales, 1 = opportunity, 2 = change
	QuoteType float32 `json:"quoteType,omitempty"`
}
