/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ICharacteristicValue struct {
	// The unique ID of the characteristic
	ValueID string `json:"ValueID,omitempty"`
	// Description of the selected value
	ValueDetail string `json:"ValueDetail,omitempty"`
}
