/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ErrorUnknown struct {
	Error string `json:"error,omitempty"`
}

type EvaluateValidationResponse struct {
	Valid            bool               `json:"valid,omitempty"`
	Errors           []ErrorUnknown     `json:"errors,omitempty"`
	ProductCandidate []ProductCandidate `json:"productCandidate,omitempty"`
}
