/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type UpdateQuoteNameResponse struct {
	// Quote ID
	Id string `json:"id,omitempty"`
	// The Updated Quote name
	Name string `json:"name,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
}
