/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Defines the filters to apply to the results, this is dynamic, so you can specify any names that match your location data. You can specify multiple criteria for each filter
type LocationFilterOptions struct {
	LocationId []string `json:"locationId,omitempty"`
}
