/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SummarisedPeriodicities struct {
	Periodicity string `json:"Periodicity,omitempty"`
	Rate float32 `json:"Rate,omitempty"`
}
