/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EvaluateValidationResponse500 struct {
	ResponseCode string `json:"responseCode"`
	HttpStatus float32 `json:"httpStatus"`
	ResponseText string `json:"responseText"`
	ExceptionType string `json:"exceptionType,omitempty"`
}
