/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IProfitSummary struct {
	// The value of the charge for the item on the summary.
	ItemCharge string `json:"ItemCharge,omitempty"`
	// The value of the cost for the item on the summary.
	ItemCost string `json:"ItemCost,omitempty"`
	// The value of the profit for the item on the summary - Profit is calculated using the cost and charge.
	Profit string `json:"Profit,omitempty"`
	// The value of the profit margin for the item on the summary - Profit margin is calculated as a percentage.
	ProfitMargin string `json:"ProfitMargin,omitempty"`
}
