/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IConfiguredValueUse struct {
	// Unique ID for the configured value use
	UseID string `json:"UseID,omitempty"`
	// Name of the UseArea
	UseArea string `json:"UseArea,omitempty"`
	// An array of configured values
	Value []IConfiguredValue `json:"Value,omitempty"`
	// The characteristic id
	CharacteristicID string `json:"CharacteristicID,omitempty"`
}
