/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CustomerContact struct {
	Id string `json:"id,omitempty"`
	Title string `json:"title,omitempty"`
	Firstname string `json:"firstname,omitempty"`
	Lastname string `json:"lastname,omitempty"`
	MailingAddress *CustomerAddress `json:"mailingAddress,omitempty"`
	Phone string `json:"phone,omitempty"`
	Mobile string `json:"mobile,omitempty"`
	Email string `json:"email,omitempty"`
	Description string `json:"description,omitempty"`
}
