/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SparseEntity struct {
	// The unique ID of the product
	Path string `json:"path,omitempty"`
	// Item action refer to action perform using sparse entity
	ItemAction string `json:"itemAction,omitempty"`
}
