/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ICpqItemPricing struct {
	// Date of creation
	CreationDate string `json:"CreationDate,omitempty"`
	ProductCandidate *IPricingServiceResponseEntity `json:"ProductCandidate,omitempty"`
	PriceSummary *IItemPriceSummary `json:"PriceSummary,omitempty"`
	TotalPriceSummary *ITotalProfitSummary `json:"TotalPriceSummary,omitempty"`
	PaidTotalPriceSummary *ITotalProfitSummary `json:"PaidTotalPriceSummary,omitempty"`
	// The itemised pricing summaries for unpaid instances
	ItemisedPricingSummary []IEntityProfitSummary `json:"ItemisedPricingSummary,omitempty"`
	// The itemised pricing summaries for paid instances
	PaidItemisedPricingSummary []IEntityProfitSummary `json:"PaidItemisedPricingSummary,omitempty"`
}
