/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CustomerMappingModel struct {
	// The Framework Contract that is associated with the customer identifier.  A UUID representing the instance of the document entry in the Contracts collection
	ContractId string `json:"contractId,omitempty"`
	// customer identifier, source from external
	CustomerId string `json:"customerId,omitempty"`
	// End date from when the Customer Mapping is no longer effect represented in ISO 8601 format
	EndDate string `json:"endDate,omitempty"`
	// The Digit identifier of the Framework Contract that associated with the customer identifier
	FcId string `json:"fc_Id,omitempty"`
	// Start date from when the Customer Mapping is to take effect represented in ISO 8601 format
	StartDate string `json:"startDate,omitempty"`
}
