/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ValidationError struct {
	EntityID string `json:"entityID,omitempty"`
	EntityUniqueCode string `json:"entityUniqueCode,omitempty"`
	ChildID string `json:"childID,omitempty"`
	ErrorCode string `json:"errorCode,omitempty"`
	Message string `json:"message,omitempty"`
	FriendlyMessage string `json:"friendlyMessage,omitempty"`
	XsiType string `json:"xsiType,omitempty"`
}
