/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BreakdownData struct {
	Name *BreakdownName `json:"name,omitempty"`
	Type_ *BreakdownType `json:"type,omitempty"`
	Period *BreakdownPeriod `json:"period,omitempty"`
	Quantity *BreakdownQuantity `json:"quantity,omitempty"`
	UnitCost *BreakdownQuantity `json:"unitCost,omitempty"`
	UnitPrice *BreakdownQuantity `json:"unitPrice,omitempty"`
	UnitProfit *BreakdownQuantity `json:"unitProfit,omitempty"`
	TotalCost *BreakdownQuantity `json:"totalCost,omitempty"`
	TotalPrice *BreakdownQuantity `json:"totalPrice,omitempty"`
	TotalProfit *BreakdownQuantity `json:"totalProfit,omitempty"`
	ProfitMargin *BreakdownQuantity `json:"profitMargin,omitempty"`
}
