/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IEntity struct {
	// Unique ID for the entity instance
	ID string `json:"ID,omitempty"`
	// ID of the entity according to its specification
	EntityID string `json:"EntityID,omitempty"`
	// An array of related entities
	ChildEntity []IEntity `json:"ChildEntity,omitempty"`
	//  An array of characteristic uses. Can be configurable characteristic or fact instances
	CharacteristicUse []ICharacteristicUse `json:"CharacteristicUse,omitempty"`
	//  An array of rating attributes
	RateAttribute []IRatingAttribute `json:"RateAttribute,omitempty"`
	//  An array of configured value uses. These are user defined characteristic instances
	ConfiguredValue []IConfiguredValueUse `json:"ConfiguredValue,omitempty"`
	IsNewForCustomer bool `json:"_IsNewForCustomer,omitempty"`
}
