/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QuoteItemCreateBody struct {
	ProductId string `json:"productId,omitempty"`
	LinkedItemId string `json:"linkedItemId,omitempty"`
	ItemAction string `json:"itemAction,omitempty"`
	QuoteLastUpdated string `json:"quoteLastUpdated,omitempty"`
}
