/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CustomerAddress struct {
	StreetAddress1 string `json:"streetAddress1,omitempty"`
	StreetAddress2 string `json:"streetAddress2,omitempty"`
	City string `json:"city,omitempty"`
	CountyState string `json:"county-state,omitempty"`
	Country string `json:"country,omitempty"`
	PostalcodeZip string `json:"postalcode-zip,omitempty"`
}
