/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ExternalReservationObject struct {
	RequestedValue string `json:"requestedValue,omitempty"`
	AllocatedValue string `json:"allocatedValue,omitempty"`
	ExternalReservationResult *ExternalReservationObjectExternalReservationResult `json:"ExternalReservationResult,omitempty"`
	ErrorMessage string `json:"errorMessage,omitempty"`
}
