/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TotalSummaryData struct {
	Period *BreakdownSummaryPeriod `json:"period,omitempty"`
	Cost *BreakdownQuantity `json:"cost,omitempty"`
	Price *BreakdownQuantity `json:"price,omitempty"`
	Profit *BreakdownQuantity `json:"profit,omitempty"`
	ProfitMargin *BreakdownQuantity `json:"profitMargin,omitempty"`
}
