/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetOrderEnrichmentTask200 struct {
	OrderNumber string `json:"orderNumber,omitempty"`
	OrderStatus string `json:"orderStatus,omitempty"`
	OrderCreationDate *GetOrderEnrichmentTask200OrderCreationDate `json:"orderCreationDate,omitempty"`
	OrderEnrichmentTasks []GetOrderEnrichmentTask200OrderEnrichmentTasks `json:"orderEnrichmentTasks,omitempty"`
}
