/*
 * CPQ
 *
 * CPQ Web API Documentation
 *
 * API version: 2.9.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OrderItem struct {
	Status string `json:"Status,omitempty"`
	PONR string `json:"PONR,omitempty"`
	OrderKey string `json:"OrderKey,omitempty"`
	OrderSpecKey string `json:"OrderSpecKey,omitempty"`
	EntitySpecKey string `json:"EntitySpecKey,omitempty"`
}
